from PyQt5 import QtCore, QtGui, QtWidgets
from Admin.Cliente.Model.Cliente import Cliente
from Metodi_gestione_oggetti.GestioneOggetti import GestioneOggetti
import shutil
import os
from Dieta.Controller.Dieta_cliente_controller import metodi_dieta_cliente

class dieta_staff(object):

    objMetodi = GestioneOggetti()
    objCliente = Cliente()
    peso = 0
    Controller = metodi_dieta_cliente()
    percorso_file_dieta_personali = "./Dieta/Data/Files_diete_personali/"


    def apriFile(self):
        percorso = self.Controller.allegaFile()
        if percorso != "":
            estensione = percorso.split(".")
            indice = len(estensione)
            self.Controller.eliminaFileDietaVecchi(self.percorso_file_dieta_personali, self.utente_da_visualizzare)
            shutil.copy(percorso, "./Dieta/Data/files_diete_personali/" + self.utente_da_visualizzare + "." + estensione[indice - 1])
            self.objMetodi.show_popup_ok("il file è stato inviato correttamente!")
            self.scheda_dieta.close()
        else:
            self.objMetodi.show_popup_exception("Errore")


    def popola_dati_fisiologici(self):
        oggetto_info = self.Controller.getOggetto(self.utente_da_visualizzare)
        if oggetto_info != 0:
            self.txtBmi.setText(oggetto_info.bmi)
            self.txtPesoIdeale.setText(oggetto_info.peso_ideale)
            self.txtFabbisogno.setText(oggetto_info.fabbisogno)
            self.plainTextEdit.setPlainText(oggetto_info.segnalazioni)
        else:
            self.objMetodi.show_popup_exception("Dati non indicati.")

    def nascondi(self):
        self.label_15.hide()
        self.lblConsiglioDieta.hide()
        self.label_23.hide()
        self.lblSuggerimento.hide()
        self.label_20.hide()
        self.txtCarbo.hide()
        self.label_21.hide()
        self.txtGrassi.hide()
        self.label_17.hide()
        self.txtProteine.hide()
        self.btnCalcolaNutrienti.hide()
        self.label_18.hide()
        self.txtRisultato.hide()
        self.listWidget_3.hide()

    def appari(self):
        oggetto_info = self.Controller.getOggetto(self.utente_da_visualizzare)
        if oggetto_info != 0:
            self.plainTextEdit.hide()
            self.label_15.show()
            self.lblConsiglioDieta.show()
            self.label_23.show()
            self.lblSuggerimento.show()
            self.label_20.show()
            self.txtCarbo.show()
            self.label_21.show()
            self.txtGrassi.show()
            self.label_17.show()
            self.txtProteine.show()
            self.btnCalcolaNutrienti.show()
            self.label_18.show()
            self.txtRisultato.show()
            self.listWidget_3.show()
            self.popola_mostra_suggerimenti()
        else:
            self.objMetodi.show_popup_ok('il cliente non ha ancora indicato i dati fisiologici')

    def popola_mostra_suggerimenti(self):
        self.peso = self.Controller.getPeso(self.utente_da_visualizzare)
        if self.peso != 0:
            if self.peso < self.txtPesoIdeale.text():
                self.lblConsiglioDieta.setText("dieta ipercalorica")
                self.lblSuggerimento.setText("maggiore di " + self.txtFabbisogno.text() + " kcal ")
            else:
                self.lblConsiglioDieta.setText("dieta ipocalorica")
                self.lblSuggerimento.setText("minore di " + self.txtFabbisogno.text() + " kcal ")
        else:
            self.lblConsiglioDieta.setText("Peso non indicato.")
            self.lblSuggerimento.clear()

    def calcola(self):
        try:
            carboidrati = float(self.txtCarbo.text())
            grassi = float(self.txtGrassi.text())
            proteine = float(self.txtProteine.text())
            fabbisogno = str(carboidrati * 4 + grassi * 9 + proteine * 4)
            self.txtRisultato.setText(fabbisogno + " Kcal ")
        except(Exception):
            self.txtCarbo.clear()
            self.txtProteine.clear()
            self.txtGrassi.clear()


    def setupUi(self, MainWindow, cliente):
        self.utente_da_visualizzare = cliente
        self.scheda_dieta = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 567)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblNome = QtWidgets.QLabel(self.centralwidget)
        self.lblNome.setGeometry(QtCore.QRect(10, 10, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblNome.setFont(font)
        self.lblNome.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(135, 60, 291, 101))
        self.listWidget.setObjectName("listWidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(166, 39, 161, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 70, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtBmi = QtWidgets.QLineEdit(self.centralwidget)
        self.txtBmi.setGeometry(QtCore.QRect(290, 70, 113, 21))
        self.txtBmi.setText("")
        self.txtBmi.setReadOnly(True)
        self.txtBmi.setObjectName("lineEdit")
        self.txtPesoIdeale = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPesoIdeale.setGeometry(QtCore.QRect(290, 100, 113, 21))
        self.txtPesoIdeale.setText("")
        self.txtPesoIdeale.setReadOnly(True)
        self.txtPesoIdeale.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 100, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtFabbisogno = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFabbisogno.setGeometry(QtCore.QRect(290, 130, 113, 21))
        self.txtFabbisogno.setText("")
        self.txtFabbisogno.setReadOnly(True)
        self.txtFabbisogno.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(140, 130, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btnAllegaFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnAllegaFile.setGeometry(QtCore.QRect(160, 460, 261, 31))
        self.btnAllegaFile.setObjectName("pushButton_3")
        self.listWidget_3 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_3.setGeometry(QtCore.QRect(40, 200, 481, 241))
        self.listWidget_3.setObjectName("listWidget_3")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(50, 210, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(100, 370, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(50, 370, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.btnCalcolaNutrienti = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalcolaNutrienti.setGeometry(QtCore.QRect(240, 370, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnCalcolaNutrienti.setFont(font)
        self.btnCalcolaNutrienti.setObjectName("pushButton_4")
        self.txtProteine = QtWidgets.QLineEdit(self.centralwidget)
        self.txtProteine.setGeometry(QtCore.QRect(130, 370, 91, 20))
        self.txtProteine.setObjectName("lineEdit_7")
        self.txtCarbo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCarbo.setGeometry(QtCore.QRect(130, 310, 91, 20))
        self.txtCarbo.setObjectName("lineEdit_8")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(50, 400, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.txtRisultato = QtWidgets.QLabel(self.centralwidget)
        self.txtRisultato.setGeometry(QtCore.QRect(350, 400, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtRisultato.setFont(font)
        self.txtRisultato.setText("")
        self.txtRisultato.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(50, 310, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(50, 340, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.txtGrassi = QtWidgets.QLineEdit(self.centralwidget)
        self.txtGrassi.setGeometry(QtCore.QRect(130, 340, 91, 20))
        self.txtGrassi.setObjectName("lineEdit_9")
        self.lblConsiglioDieta = QtWidgets.QLabel(self.centralwidget)
        self.lblConsiglioDieta.setGeometry(QtCore.QRect(220, 240, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblConsiglioDieta.setFont(font)
        self.lblConsiglioDieta.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(50, 260, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.lblSuggerimento = QtWidgets.QLabel(self.centralwidget)
        self.lblSuggerimento.setGeometry(QtCore.QRect(120, 290, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblSuggerimento.setFont(font)
        self.lblSuggerimento.setObjectName("label_24")
        self.rbtnSuggerimenti = QtWidgets.QRadioButton(self.centralwidget)
        self.rbtnSuggerimenti.setGeometry(QtCore.QRect(40, 180, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.rbtnSuggerimenti.setFont(font)
        self.rbtnSuggerimenti.setObjectName("radioButton")
        self.rbtnNoteCliente = QtWidgets.QRadioButton(self.centralwidget)
        self.rbtnNoteCliente.setGeometry(QtCore.QRect(310, 180, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.rbtnNoteCliente.setFont(font)
        self.rbtnNoteCliente.setObjectName("radioButton_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 200, 481, 241))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 566, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.plainTextEdit.hide()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.lblNome.setText(self.utente_da_visualizzare)
        self.nascondi()
        self.rbtnSuggerimenti.clicked.connect(self.appari)
        self.btnAllegaFile.clicked.connect(self.apriFile)
        self.popola_dati_fisiologici()
        self.rbtnNoteCliente.clicked.connect(self.plainTextEdit.show)
        self.btnCalcolaNutrienti.clicked.connect(self.calcola)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Assegna dieta"))
        self.lblNome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Faccenda Andrea</p><p align=\"center\"><br/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Dati fisiologici:</p><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>BMI:</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Peso forma:</p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Fabbisogno:</p><p><br/></p></body></html>"))
        self.btnAllegaFile.setText(_translate("MainWindow", "Allega file dieta"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Dopo aver analizzato i dati fisiologici-metabolici</p><p> è consigliata una dieta:</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Proteine:<br/></p></body></html>"))
        self.btnCalcolaNutrienti.setText(_translate("MainWindow", "CALCOLA"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p>Kcal totali dopo aver inserito le grammature:</p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p>Carboidrati:</p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>Grassi:</p></body></html>"))
        self.lblConsiglioDieta.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>Con un fabbisogno calorico giornaliero</p><p></p></body></html>"))
        self.lblSuggerimento.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.rbtnSuggerimenti.setText(_translate("MainWindow", "Mostra suggerimenti"))
        self.rbtnNoteCliente.setText(_translate("MainWindow", "Mostra note del cliente"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = dieta_staff()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


