from PyQt5 import QtCore, QtGui, QtWidgets
from Cliente.Allenamenti.Controller.Esercizi_controller import metodi_esercizi
from Metodi_gestione_oggetti.GestioneOggetti import GestioneOggetti


class allenamento(object):

    username = ""
    objMetodi = GestioneOggetti()
    Controller = metodi_esercizi()
    vettore_preferenze = []

    def popolaArray(self):
        self.vettore_preferenze.clear()
        if self.checkBox.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox.text())
        if self.checkBox_2.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_2.text())
        if self.checkBox_3.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_3.text())
        if self.checkBox_4.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_4.text())
        if self.checkBox_5.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_5.text())
        if self.checkBox_6.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_6.text())
        if self.checkBox_7.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_7.text())
        if self.checkBox_8.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_8.text())
        if self.checkBox_9.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_9.text())
        if self.checkBox_10.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_10.text())
        if self.checkBox_11.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_11.text())
        if self.checkBox_12.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_12.text())
        if self.checkBox_13.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_13.text())
        if self.checkBox_14.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_14.text())
        if self.checkBox_15.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_15.text())
        if self.checkBox_16.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_16.text())
        if self.checkBox_17.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_17.text())
        if self.checkBox_18.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_18.text())
        if self.checkBox_19.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_19.text())
        if self.checkBox_20.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_20.text())
        if self.checkBox_21.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_21.text())
        if self.checkBox_22.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_22.text())
        if self.checkBox_23.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_23.text())
        if self.checkBox_24.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_24.text())
        if self.checkBox_25.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_25.text())
        if self.checkBox_26.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_26.text())
        if self.checkBox_27.isChecked() is True:
            self.vettore_preferenze.append(self.checkBox_27.text())

    def salvaEsercizio(self):
        try:
            self.popolaArray()
            self.Controller.creaOggetto(self.username, self.vettore_preferenze)
            self.objMetodi.show_popup_ok("Esercizi salvati con successo!")
        except Exception:
            self.objMetodi.show_popup_exception("Errore imprevisto.")
        self.finestra.close()

    def setupUi(self, MainWindow,username):
        self.finestra = MainWindow
        self.username = username
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 781, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setGeometry(QtCore.QRect(10, 10, 111, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setGeometry(QtCore.QRect(370, 10, 87, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 220, 87, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_4.setGeometry(QtCore.QRect(370, 220, 151, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 50, 161, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/alzateverticali1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 250, 291, 171))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/Senza_titolo_1.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(420, 40, 301, 161))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/Kettlebell.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(380, 270, 291, 141))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/Alzatebustoinclinato.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(150, 60, 151, 131))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/alzateverticali2.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_6.setGeometry(QtCore.QRect(400, 10, 161, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_7.setGeometry(QtCore.QRect(10, 230, 141, 20))
        self.checkBox_7.setObjectName("checkBox_7")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 45, 261, 161))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/Pancapiana.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(389, 45, 141, 141))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/aperturepancapiana.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(570, 50, 141, 131))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/aperturepnacapiana2.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(9, 275, 121, 131))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/pettorali-spinte-manubri-panca-piana-ag.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(150, 270, 131, 131))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("./Resources/images/estensionemanubri2.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_8.setGeometry(QtCore.QRect(10, 10, 171, 20))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 230, 151, 20))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_10.setGeometry(QtCore.QRect(390, 10, 191, 20))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_11.setGeometry(QtCore.QRect(390, 230, 201, 20))
        self.checkBox_11.setObjectName("checkBox_11")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 281, 141))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/RematoreBilanciere.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(400, 60, 251, 131))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/RematoreBusto90.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(10, 260, 161, 151))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/PancaRematore.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(389, 265, 141, 141))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/dorsali-trazioni-2.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(550, 270, 141, 141))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/dorsali-trazioni-1.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 10, 111, 20))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_13.setGeometry(QtCore.QRect(430, 10, 121, 20))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_14.setGeometry(QtCore.QRect(10, 230, 191, 20))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_15.setGeometry(QtCore.QRect(430, 230, 111, 20))
        self.checkBox_15.setObjectName("checkBox_15")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(20, 50, 281, 141))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/CurlBilanciere.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(430, 50, 291, 141))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/CurlCaviBassi.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(10, 260, 161, 151))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/BicipitiPanca1.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(180, 260, 151, 151))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("./Downloads/Panca2.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(420, 260, 301, 151))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/CurlManubri.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_16.setGeometry(QtCore.QRect(10, 10, 171, 20))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_17.setGeometry(QtCore.QRect(400, 10, 101, 20))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_18.setGeometry(QtCore.QRect(10, 220, 151, 20))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_19.setGeometry(QtCore.QRect(410, 220, 151, 20))
        self.checkBox_19.setObjectName("checkBox_19")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(10, 40, 251, 151))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/FrenchPressManubrio.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(400, 50, 161, 141))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/TricipitCavi1.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(10, 250, 271, 151))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/SpintePanca90Tricipiti.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(400, 240, 161, 161))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/Tricipitiestensionimanubri1.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(550, 50, 161, 141))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/TricipitCavi2.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(570, 270, 161, 121))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/Tricipitiestensionimanubri2.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.checkBox_20 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_20.setGeometry(QtCore.QRect(10, 10, 121, 20))
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_21.setGeometry(QtCore.QRect(400, 10, 211, 20))
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_22.setGeometry(QtCore.QRect(10, 220, 161, 20))
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_23.setGeometry(QtCore.QRect(400, 220, 221, 20))
        self.checkBox_23.setObjectName("checkBox_23")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(10, 60, 121, 141))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/SquatBilanciere1.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_5)
        self.label_28.setGeometry(QtCore.QRect(140, 60, 131, 141))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/SquatBilanciere2png.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(10, 250, 121, 141))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/Affondo1.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setGeometry(QtCore.QRect(120, 240, 141, 141))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/Affondo2.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setGeometry(QtCore.QRect(400, 250, 141, 141))
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/Stacco1.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_5)
        self.label_32.setGeometry(QtCore.QRect(440, 60, 181, 151))
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/Stacchipolpacci.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_5)
        self.label_33.setGeometry(QtCore.QRect(560, 250, 161, 141))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/Stacco2.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.checkBox_24 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_24.setGeometry(QtCore.QRect(10, 10, 87, 20))
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_25.setGeometry(QtCore.QRect(10, 210, 111, 20))
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_26 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_26.setGeometry(QtCore.QRect(430, 10, 87, 20))
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_27 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_27.setGeometry(QtCore.QRect(430, 200, 161, 20))
        self.checkBox_27.setObjectName("checkBox_27")
        self.label_34 = QtWidgets.QLabel(self.tab_6)
        self.label_34.setGeometry(QtCore.QRect(70, 0, 151, 171))
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/Plank.png"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_6)
        self.label_35.setGeometry(QtCore.QRect(10, 270, 151, 131))
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/AddominaliCrissCross1.png"))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_6)
        self.label_36.setGeometry(QtCore.QRect(520, 250, 161, 141))
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/TorsioniWallball.png"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_6)
        self.label_37.setGeometry(QtCore.QRect(470, 30, 171, 151))
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/Crunch.png"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_6)
        self.label_38.setGeometry(QtCore.QRect(180, 260, 161, 141))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("./Resources/images/PngAllenamenti/AddominaliCrissCross2.png"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.tabWidget.addTab(self.tab_6, "")
        self.btn_salva = QtWidgets.QPushButton(self.centralwidget)
        self.btn_salva.setGeometry(QtCore.QRect(320, 510, 161, 28))
        self.btn_salva.setObjectName("btn_salva")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn_salva.clicked.connect(self.salvaEsercizio)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Allenamento"))
        self.checkBox.setText(_translate("MainWindow", "Alzate Verticali"))
        self.checkBox_2.setText(_translate("MainWindow", "Alzate Laterali"))
        self.checkBox_3.setText(_translate("MainWindow", "Cavi"))
        self.checkBox_4.setText(_translate("MainWindow", "Alzate Busto Inclinato"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Spalle"))
        self.checkBox_5.setText(_translate("MainWindow", "Panca Piana"))
        self.checkBox_6.setText(_translate("MainWindow", "Aperture Panca Piana"))
        self.checkBox_7.setText(_translate("MainWindow", "Spinte Panca Piana"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Petto"))
        self.checkBox_8.setText(_translate("MainWindow", "Rematore con Bilanciere"))
        self.checkBox_9.setText(_translate("MainWindow", "Rematore con Panca"))
        self.checkBox_10.setText(_translate("MainWindow", "Rematore con Busto a 90°"))
        self.checkBox_11.setText(_translate("MainWindow", "Trazioni Tbar con Bilanciere"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Dorsali"))
        self.checkBox_12.setText(_translate("MainWindow", "Curl Bilanciere"))
        self.checkBox_13.setText(_translate("MainWindow", "Curl Cavi Bassi"))
        self.checkBox_14.setText(_translate("MainWindow", "Curl con Manubri e  Panca"))
        self.checkBox_15.setText(_translate("MainWindow", "Curl Manubri"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Bicipiti"))
        self.checkBox_16.setText(_translate("MainWindow", "French Press Manubrio"))
        self.checkBox_17.setText(_translate("MainWindow", "Tricipit Cavi"))
        self.checkBox_18.setText(_translate("MainWindow", "Spinte Panca Piana"))
        self.checkBox_19.setText(_translate("MainWindow", "Estensione Manubri"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tricipiti"))
        self.checkBox_20.setText(_translate("MainWindow", "Squat Bilanciere"))
        self.checkBox_21.setText(_translate("MainWindow", "Spinta Polpacci con Bilanciere"))
        self.checkBox_22.setText(_translate("MainWindow", "Affondi con Bilanciere"))
        self.checkBox_23.setText(_translate("MainWindow", "Stacco da Terra con Bilanciere"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Gambe"))
        self.checkBox_24.setText(_translate("MainWindow", "Plank"))
        self.checkBox_25.setText(_translate("MainWindow", "Criss Cross"))
        self.checkBox_26.setText(_translate("MainWindow", "Crunch"))
        self.checkBox_27.setText(_translate("MainWindow", "Torsioni con Wallball"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Addome"))
        self.btn_salva.setText(_translate("MainWindow", "Salva"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = allenamento()
    ui.setupUi(MainWindow,username = "")
    MainWindow.show()
    sys.exit(app.exec_())