from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate
from Metodi_gestione_oggetti.GestioneOggetti import GestioneOggetti
from Gestione_allenamento.Controller.Scheda_allenamento_controller import metodi_scheda_allenamento

class allenamento_staff(object):
    Controller = metodi_scheda_allenamento()
    username = ""
    lista_esercizi = []
    objMetodi = GestioneOggetti()
    nome_esercizi = []
    numero_esercizi = []

    def carica_lista(self):
        lista = []
        self.listWidget.clear()
        if self.checkBox.checkState():
            lista.append(self.checkBox.text())
        if self.checkBox_2.checkState():
            lista.append(self.checkBox_2.text())
        if self.checkBox_3.checkState():
            lista.append(self.checkBox_3.text())
        if self.checkBox_4.checkState():
            lista.append(self.checkBox_4.text())
        if self.checkBox_5.checkState():
            lista.append(self.checkBox_5.text())
        if self.checkBox_6.checkState():
            lista.append(self.checkBox_6.text())
        if self.checkBox_7.checkState():
            lista.append(self.checkBox_7.text())
        if self.checkBox_8.checkState():
            lista.append(self.checkBox_8.text())
        if self.checkBox_9.checkState():
            lista.append(self.checkBox_9.text())
        if self.checkBox_10.checkState():
            lista.append(self.checkBox_10.text())
        if self.checkBox_11.checkState():
            lista.append(self.checkBox_11.text())
        if self.checkBox_12.checkState():
            lista.append(self.checkBox_12.text())
        if self.checkBox_13.checkState():
            lista.append(self.checkBox_13.text())
        if self.checkBox_14.checkState():
            lista.append(self.checkBox_14.text())
        if self.checkBox_15.checkState():
            lista.append(self.checkBox_15.text())
        if self.checkBox_16.checkState():
            lista.append(self.checkBox_16.text())
        if self.checkBox_17.checkState():
            lista.append(self.checkBox_17.text())
        if self.checkBox_18.checkState():
            lista.append(self.checkBox_18.text())
        if self.checkBox_19.checkState():
            lista.append(self.checkBox_19.text())
        if self.checkBox_20.checkState():
            lista.append(self.checkBox_20.text())
        if self.checkBox_21.checkState():
            lista.append(self.checkBox_21.text())
        if self.checkBox_22.checkState():
            lista.append(self.checkBox_22.text())
        if self.checkBox_23.checkState():
            lista.append(self.checkBox_23.text())
        if self.checkBox_24.checkState():
            lista.append(self.checkBox_24.text())
        if self.checkBox_25.checkState():
            lista.append(self.checkBox_25.text())
        if self.checkBox_26.checkState():
            lista.append(self.checkBox_26.text())
        if self.checkBox_27.checkState():
            lista.append(self.checkBox_27.text())
        if self.checkBox_28.checkState():
            lista.append(self.checkBox_28.text())
        if self.checkBox_29.checkState():
            lista.append(self.checkBox_29.text())
        if self.checkBox_30.checkState():
            lista.append(self.checkBox_30.text())
        if self.checkBox_31.checkState():
            lista.append(self.checkBox_31.text())
        if self.checkBox_32.checkState():
            lista.append(self.checkBox_32.text())
        if self.checkBox_33.checkState():
            lista.append(self.checkBox_33.text())
        if self.checkBox_34.checkState():
            lista.append(self.checkBox_34.text())
        if self.checkBox_35.checkState():
            lista.append(self.checkBox_35.text())
        if self.checkBox_36.checkState():
            lista.append(self.checkBox_36.text())
        if self.checkBox_37.checkState():
            lista.append(self.checkBox_37.text())
        if self.checkBox_38.checkState():
            lista.append(self.checkBox_38.text())
        if self.checkBox_39.checkState():
            lista.append(self.checkBox_39.text())
        if self.checkBox_40.checkState():
            lista.append(self.checkBox_40.text())
        if self.checkBox_41.checkState():
            lista.append(self.checkBox_41.text())
        if self.checkBox_42.checkState():
            lista.append(self.checkBox_42.text())
        if self.checkBox_43.checkState():
            lista.append(self.checkBox_43.text())
        if self.checkBox_44.checkState():
            lista.append(self.checkBox_44.text())
        if self.checkBox_45.checkState():
            lista.append(self.checkBox_45.text())
        if self.checkBox_46.checkState():
            lista.append(self.checkBox_46.text())
        if self.checkBox_47.checkState():
            lista.append(self.checkBox_47.text())
        if self.checkBox_48.checkState():
            lista.append(self.checkBox_48.text())
        if self.checkBox_49.checkState():
            lista.append(self.checkBox_49.text())
        if self.checkBox_50.checkState():
            lista.append(self.checkBox_50.text())
        if self.checkBox_51.checkState():
            lista.append(self.checkBox_51.text())
        if self.checkBox_52.checkState():
            lista.append(self.checkBox_52.text())
        if self.checkBox_53.checkState():
            lista.append(self.checkBox_53.text())
        if self.checkBox_54.checkState():
            lista.append(self.checkBox_54.text())
        if self.checkBox_55.checkState():
            lista.append(self.checkBox_55.text())
        if self.checkBox_56.checkState():
            lista.append(self.checkBox_56.text())
        if self.checkBox_57.checkState():
            lista.append(self.checkBox_57.text())
        if self.checkBox_58.checkState():
            lista.append(self.checkBox_58.text())
        if self.checkBox_59.checkState():
            lista.append(self.checkBox_59.text())
        if self.checkBox_60.checkState():
            lista.append(self.checkBox_60.text())
        if self.checkBox_61.checkState():
            lista.append(self.checkBox_61.text())
        if self.checkBox_62.checkState():
            lista.append(self.checkBox_62.text())
        if self.checkBox_63.checkState():
            lista.append(self.checkBox_63.text())
        if self.checkBox_64.checkState():
            lista.append(self.checkBox_64.text())
        if self.checkBox_65.checkState():
            lista.append(self.checkBox_65.text())
        if self.checkBox_66.checkState():
            lista.append(self.checkBox_66.text())
        if self.checkBox_67.checkState():
            lista.append(self.checkBox_67.text())
        if self.checkBox_68.checkState():
            lista.append(self.checkBox_68.text())
        if self.checkBox_69.checkState():
            lista.append(self.checkBox_69.text())
        if self.checkBox_70.checkState():
            lista.append(self.checkBox_70.text())
        if self.checkBox_71.checkState():
            lista.append(self.checkBox_71.text())
        if self.checkBox_72.checkState():
            lista.append(self.checkBox_72.text())
        if self.checkBox_73.checkState():
            lista.append(self.checkBox_73.text())
        if self.checkBox_74.checkState():
            lista.append(self.checkBox_74.text())
        if self.checkBox_75.checkState():
            lista.append(self.checkBox_75.text())
        if self.checkBox_76.checkState():
            lista.append(self.checkBox_76.text())
        if self.checkBox_77.checkState():
            lista.append(self.checkBox_77.text())
        if self.checkBox_78.checkState():
            lista.append(self.checkBox_78.text())
        if self.checkBox_79.checkState():
            lista.append(self.checkBox_79.text())
        if self.checkBox_80.checkState():
            lista.append(self.checkBox_80.text())
        if self.checkBox_81.checkState():
            lista.append(self.checkBox_81.text())
        if self.checkBox_82.checkState():
            lista.append(self.checkBox_82.text())
        if self.checkBox_83.checkState():
            lista.append(self.checkBox_83.text())
        if self.checkBox_84.checkState():
            lista.append(self.checkBox_84.text())
        if self.checkBox_85.checkState():
            lista.append(self.checkBox_85.text())
        if self.checkBox_86.checkState():
            lista.append(self.checkBox_86.text())
        if self.checkBox_87.checkState():
            lista.append(self.checkBox_87.text())
        if self.checkBox_88.checkState():
            lista.append(self.checkBox_88.text())
        if self.checkBox_89.checkState():
            lista.append(self.checkBox_89.text())
        if self.checkBox_90.checkState():
            lista.append(self.checkBox_90.text())
        if self.checkBox_91.checkState():
            lista.append(self.checkBox_91.text())
        if self.checkBox_92.checkState():
            lista.append(self.checkBox_92.text())
        if self.checkBox_93.checkState():
            lista.append(self.checkBox_93.text())
        if self.checkBox_94.checkState():
            lista.append(self.checkBox_94.text())
        if self.checkBox_95.checkState():
            lista.append(self.checkBox_95.text())
        if self.checkBox_97.checkState():
            lista.append(self.checkBox_97.text())
        if self.checkBox_98.checkState():
            lista.append(self.checkBox_98.text())
        if self.checkBox_100.checkState():
            lista.append(self.checkBox_100.text())
        if self.checkBox_101.checkState():
            lista.append(self.checkBox_101.text())
        if self.checkBox_102.checkState():
            lista.append(self.checkBox_102.text())
        if self.checkBox_103.checkState():
            lista.append(self.checkBox_103.text())
        if self.checkBox_105.checkState():
            lista.append(self.checkBox_105.text())
        if self.checkBox_107.checkState():
            lista.append(self.checkBox_107.text())
        if self.checkBox_108.checkState():
            lista.append(self.checkBox_108.text())
        if self.checkBox_110.checkState():
            lista.append(self.checkBox_110.text())
        for elem in lista:
            self.listWidget.addItem(elem)

    def pulisci_lista(self):
        self.listWidget.clear()

    def nascondi(self):
        self.label_5.hide()
        self.label_6.hide()
        self.label_7.hide()
        self.txtNumeroSerie.hide()
        self.txtNumeroRipetizioni.hide()
        self.txtTempoRecupero.hide()
        self.btnSalvaScheda.hide()
        self.lblInfo1.hide()
        self.lblInfo2.hide()
        self.txtNumeroSerie.setText("")
        self.txtNumeroRipetizioni.setText("")
        self.txtTempoRecupero.setText("")

    def appari(self):
        self.lblSalvataggio.hide()
        self.label_5.show()
        self.label_6.show()
        self.label_7.show()
        self.txtNumeroSerie.show()
        self.txtNumeroRipetizioni.show()
        self.txtTempoRecupero.show()
        self.btnSalvaScheda.show()
        self.lblInfo1.show()
        self.lblInfo2.show()
        self.txtNumeroSerie.setText("")
        self.txtNumeroRipetizioni.setText("")
        self.txtTempoRecupero.setText("")

    def save_exercise(self):
        if self.txtNumeroSerie.text() == "" or self.txtNumeroRipetizioni.text() == "" or self.txtTempoRecupero.text() == "":
            self.objMetodi.show_popup_exception("Devi prima riempire tutte le caselle!")
        else:
            self.nome_esercizi.append(self.listWidget.currentItem().text())
            self.numero_esercizi.append(self.txtNumeroSerie.text() + "-"
                                        + self.txtNumeroRipetizioni.text() + "-" + self.txtTempoRecupero.text())

            self.txtNumeroSerie.clear()
            self.txtNumeroRipetizioni.clear()
            self.txtTempoRecupero.clear()
            self.txtNumeroSerie.setFocus()
            if self.listWidget.currentRow() != self.listWidget.count()-1:
                self.listWidget.setCurrentRow(self.listWidget.currentRow()+1)
            else:
                self.btnInvia.show()
            self.controllo_salvataggio()

    def controllo_salvataggio(self):
        for elem in self.nome_esercizi:
            if elem == self.listWidget.currentItem().text():
                self.nascondi()
                self.lblSalvataggio.show()
                return
        self.lblSalvataggio.hide()
        self.appari()

    def invia_cliente(self):
        self.Controller.creaOggetto(self.username.replace(" ", ""), self.nome_esercizi, self.numero_esercizi,
                                    self.dateEdit.text(), self.dateEdit_2.text())
        if self.Controller.controlloData():
            if self.objMetodi.show_popup_question("Sovrascrivere i dati esistenti?"):
                self.Controller.sovrascrivi()
                self.objMetodi.show_popup_ok("Salvataggio effettuato!")
        else:
            self.Controller.scrivi()
            self.objMetodi.show_popup_ok("Salvataggio effettuato!")
        self.finestra.close()

    def setupUi(self, MainWindow, username):
        self.finestra = MainWindow
        self.username = username
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 771, 491))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 121, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 70, 111, 31))
        self.label_3.setObjectName("label_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 130, 731, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 10, 671, 291))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(20, 30, 281, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 60, 281, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 90, 271, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 120, 281, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 150, 121, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_6.setGeometry(QtCore.QRect(20, 180, 181, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_7.setGeometry(QtCore.QRect(20, 210, 201, 20))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_8.setGeometry(QtCore.QRect(20, 240, 201, 20))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_9.setGeometry(QtCore.QRect(320, 210, 201, 20))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_13 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_13.setGeometry(QtCore.QRect(320, 150, 121, 20))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_10.setGeometry(QtCore.QRect(320, 30, 281, 20))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_12.setGeometry(QtCore.QRect(320, 120, 281, 20))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_11.setGeometry(QtCore.QRect(320, 180, 181, 20))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_14.setGeometry(QtCore.QRect(320, 60, 281, 20))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_15.setGeometry(QtCore.QRect(320, 240, 201, 20))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_16.setGeometry(QtCore.QRect(320, 90, 271, 20))
        self.checkBox_16.setObjectName("checkBox_16")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_17.setGeometry(QtCore.QRect(330, 170, 201, 20))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_18.setGeometry(QtCore.QRect(30, 140, 121, 20))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_19.setGeometry(QtCore.QRect(30, 200, 201, 20))
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_20.setGeometry(QtCore.QRect(330, 110, 281, 20))
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_21.setGeometry(QtCore.QRect(30, 20, 281, 20))
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_22.setGeometry(QtCore.QRect(330, 50, 281, 20))
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_23.setGeometry(QtCore.QRect(30, 110, 281, 20))
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_24.setGeometry(QtCore.QRect(30, 170, 181, 20))
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_25.setGeometry(QtCore.QRect(330, 80, 271, 20))
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_26 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_26.setGeometry(QtCore.QRect(330, 200, 201, 20))
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_27 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_27.setGeometry(QtCore.QRect(330, 20, 281, 20))
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_28 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_28.setGeometry(QtCore.QRect(30, 50, 281, 20))
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_29 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_29.setGeometry(QtCore.QRect(120, 270, 201, 20))
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_30 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_30.setGeometry(QtCore.QRect(420, 270, 201, 20))
        self.checkBox_30.setObjectName("checkBox_30")
        self.checkBox_31 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_31.setGeometry(QtCore.QRect(30, 80, 271, 20))
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_32 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_32.setGeometry(QtCore.QRect(330, 140, 251, 20))
        self.checkBox_32.setObjectName("checkBox_32")
        self.checkBox_33 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_33.setGeometry(QtCore.QRect(330, 230, 201, 20))
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkBox_34 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_34.setGeometry(QtCore.QRect(30, 230, 201, 20))
        self.checkBox_34.setObjectName("checkBox_34")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.Dorsali = QtWidgets.QWidget()
        self.Dorsali.setObjectName("Dorsali")
        self.checkBox_35 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_35.setGeometry(QtCore.QRect(330, 170, 181, 20))
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkBox_36 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_36.setGeometry(QtCore.QRect(30, 200, 201, 20))
        self.checkBox_36.setObjectName("checkBox_36")
        self.checkBox_37 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_37.setGeometry(QtCore.QRect(30, 140, 201, 20))
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_38 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_38.setGeometry(QtCore.QRect(330, 110, 281, 20))
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBox_39 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_39.setGeometry(QtCore.QRect(30, 20, 281, 20))
        self.checkBox_39.setObjectName("checkBox_39")
        self.checkBox_40 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_40.setGeometry(QtCore.QRect(330, 50, 281, 20))
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkBox_41 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_41.setGeometry(QtCore.QRect(30, 110, 281, 20))
        self.checkBox_41.setObjectName("checkBox_41")
        self.checkBox_42 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_42.setGeometry(QtCore.QRect(30, 170, 231, 20))
        self.checkBox_42.setObjectName("checkBox_42")
        self.checkBox_43 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_43.setGeometry(QtCore.QRect(330, 80, 271, 20))
        self.checkBox_43.setObjectName("checkBox_43")
        self.checkBox_44 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_44.setGeometry(QtCore.QRect(330, 20, 281, 20))
        self.checkBox_44.setObjectName("checkBox_44")
        self.checkBox_45 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_45.setGeometry(QtCore.QRect(330, 200, 231, 20))
        self.checkBox_45.setObjectName("checkBox_45")
        self.checkBox_46 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_46.setGeometry(QtCore.QRect(30, 50, 281, 20))
        self.checkBox_46.setObjectName("checkBox_46")
        self.checkBox_47 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_47.setGeometry(QtCore.QRect(30, 230, 201, 20))
        self.checkBox_47.setObjectName("checkBox_47")
        self.checkBox_48 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_48.setGeometry(QtCore.QRect(330, 230, 201, 20))
        self.checkBox_48.setObjectName("checkBox_48")
        self.checkBox_49 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_49.setGeometry(QtCore.QRect(30, 80, 271, 20))
        self.checkBox_49.setObjectName("checkBox_49")
        self.checkBox_50 = QtWidgets.QCheckBox(self.Dorsali)
        self.checkBox_50.setGeometry(QtCore.QRect(330, 140, 121, 20))
        self.checkBox_50.setObjectName("checkBox_50")
        self.tabWidget_2.addTab(self.Dorsali, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.checkBox_55 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_55.setGeometry(QtCore.QRect(60, 80, 281, 20))
        self.checkBox_55.setObjectName("checkBox_55")
        self.checkBox_62 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_62.setGeometry(QtCore.QRect(60, 110, 281, 20))
        self.checkBox_62.setObjectName("checkBox_62")
        self.checkBox_57 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_57.setGeometry(QtCore.QRect(370, 110, 281, 20))
        self.checkBox_57.setObjectName("checkBox_57")
        self.checkBox_65 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_65.setGeometry(QtCore.QRect(370, 80, 271, 20))
        self.checkBox_65.setObjectName("checkBox_65")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.checkBox_69 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_69.setGeometry(QtCore.QRect(50, 120, 271, 20))
        self.checkBox_69.setObjectName("checkBox_69")
        self.checkBox_63 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_63.setGeometry(QtCore.QRect(350, 60, 281, 20))
        self.checkBox_63.setObjectName("checkBox_63")
        self.checkBox_67 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_67.setGeometry(QtCore.QRect(350, 120, 201, 20))
        self.checkBox_67.setObjectName("checkBox_67")
        self.checkBox_60 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_60.setGeometry(QtCore.QRect(350, 150, 181, 20))
        self.checkBox_60.setObjectName("checkBox_60")
        self.checkBox_56 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_56.setGeometry(QtCore.QRect(50, 60, 281, 20))
        self.checkBox_56.setObjectName("checkBox_56")
        self.checkBox_52 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_52.setGeometry(QtCore.QRect(350, 180, 241, 20))
        self.checkBox_52.setObjectName("checkBox_52")
        self.checkBox_59 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_59.setGeometry(QtCore.QRect(50, 150, 281, 20))
        self.checkBox_59.setObjectName("checkBox_59")
        self.checkBox_66 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_66.setGeometry(QtCore.QRect(50, 90, 281, 20))
        self.checkBox_66.setObjectName("checkBox_66")
        self.checkBox_53 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_53.setGeometry(QtCore.QRect(50, 180, 121, 20))
        self.checkBox_53.setObjectName("checkBox_53")
        self.checkBox_58 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_58.setGeometry(QtCore.QRect(350, 90, 281, 20))
        self.checkBox_58.setObjectName("checkBox_58")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.checkBox_74 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_74.setGeometry(QtCore.QRect(350, 60, 281, 20))
        self.checkBox_74.setObjectName("checkBox_74")
        self.checkBox_77 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_77.setGeometry(QtCore.QRect(350, 150, 201, 20))
        self.checkBox_77.setObjectName("checkBox_77")
        self.checkBox_61 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_61.setGeometry(QtCore.QRect(50, 180, 121, 20))
        self.checkBox_61.setObjectName("checkBox_61")
        self.checkBox_76 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_76.setGeometry(QtCore.QRect(50, 90, 281, 20))
        self.checkBox_76.setObjectName("checkBox_76")
        self.checkBox_79 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_79.setGeometry(QtCore.QRect(50, 120, 271, 20))
        self.checkBox_79.setObjectName("checkBox_79")
        self.checkBox_72 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_72.setGeometry(QtCore.QRect(350, 90, 181, 20))
        self.checkBox_72.setObjectName("checkBox_72")
        self.checkBox_54 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_54.setGeometry(QtCore.QRect(350, 120, 201, 20))
        self.checkBox_54.setObjectName("checkBox_54")
        self.checkBox_68 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_68.setGeometry(QtCore.QRect(50, 60, 281, 20))
        self.checkBox_68.setObjectName("checkBox_68")
        self.checkBox_71 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_71.setGeometry(QtCore.QRect(50, 150, 281, 20))
        self.checkBox_71.setObjectName("checkBox_71")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.checkBox_88 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_88.setGeometry(QtCore.QRect(50, 130, 271, 20))
        self.checkBox_88.setObjectName("checkBox_88")
        self.checkBox_70 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_70.setGeometry(QtCore.QRect(340, 100, 231, 20))
        self.checkBox_70.setObjectName("checkBox_70")
        self.checkBox_80 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_80.setGeometry(QtCore.QRect(340, 70, 281, 20))
        self.checkBox_80.setObjectName("checkBox_80")
        self.checkBox_81 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_81.setGeometry(QtCore.QRect(340, 130, 181, 20))
        self.checkBox_81.setObjectName("checkBox_81")
        self.checkBox_75 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_75.setGeometry(QtCore.QRect(50, 70, 281, 20))
        self.checkBox_75.setObjectName("checkBox_75")
        self.checkBox_85 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_85.setGeometry(QtCore.QRect(50, 100, 281, 20))
        self.checkBox_85.setObjectName("checkBox_85")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.checkBox_95 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_95.setGeometry(QtCore.QRect(320, 140, 121, 20))
        self.checkBox_95.setObjectName("checkBox_95")
        self.checkBox_86 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_86.setGeometry(QtCore.QRect(20, 170, 211, 20))
        self.checkBox_86.setObjectName("checkBox_86")
        self.checkBox_82 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_82.setGeometry(QtCore.QRect(20, 20, 281, 20))
        self.checkBox_82.setObjectName("checkBox_82")
        self.checkBox_87 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_87.setGeometry(QtCore.QRect(320, 80, 271, 20))
        self.checkBox_87.setObjectName("checkBox_87")
        self.checkBox_83 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_83.setGeometry(QtCore.QRect(320, 50, 281, 20))
        self.checkBox_83.setObjectName("checkBox_83")
        self.checkBox_51 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_51.setGeometry(QtCore.QRect(320, 170, 341, 20))
        self.checkBox_51.setObjectName("checkBox_51")
        self.checkBox_91 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_91.setGeometry(QtCore.QRect(20, 50, 281, 20))
        self.checkBox_91.setObjectName("checkBox_91")
        self.checkBox_93 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_93.setGeometry(QtCore.QRect(320, 230, 231, 20))
        self.checkBox_93.setObjectName("checkBox_93")
        self.checkBox_94 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_94.setGeometry(QtCore.QRect(20, 80, 271, 20))
        self.checkBox_94.setObjectName("checkBox_94")
        self.checkBox_90 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_90.setGeometry(QtCore.QRect(320, 200, 271, 20))
        self.checkBox_90.setObjectName("checkBox_90")
        self.checkBox_92 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_92.setGeometry(QtCore.QRect(20, 230, 201, 20))
        self.checkBox_92.setObjectName("checkBox_92")
        self.checkBox_84 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_84.setGeometry(QtCore.QRect(20, 110, 281, 20))
        self.checkBox_84.setObjectName("checkBox_84")
        self.checkBox_64 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_64.setGeometry(QtCore.QRect(20, 200, 201, 20))
        self.checkBox_64.setObjectName("checkBox_64")
        self.checkBox_73 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_73.setGeometry(QtCore.QRect(20, 140, 161, 20))
        self.checkBox_73.setObjectName("checkBox_73")
        self.checkBox_78 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_78.setGeometry(QtCore.QRect(320, 110, 281, 20))
        self.checkBox_78.setObjectName("checkBox_78")
        self.checkBox_89 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_89.setGeometry(QtCore.QRect(320, 20, 281, 20))
        self.checkBox_89.setObjectName("checkBox_89")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.checkBox_105 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_105.setGeometry(QtCore.QRect(350, 60, 281, 20))
        self.checkBox_105.setObjectName("checkBox_105")
        self.checkBox_108 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_108.setGeometry(QtCore.QRect(50, 180, 201, 20))
        self.checkBox_108.setObjectName("checkBox_108")
        self.checkBox_97 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_97.setGeometry(QtCore.QRect(350, 180, 201, 20))
        self.checkBox_97.setObjectName("checkBox_97")
        self.checkBox_103 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_103.setGeometry(QtCore.QRect(350, 150, 181, 20))
        self.checkBox_103.setObjectName("checkBox_103")
        self.checkBox_110 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_110.setGeometry(QtCore.QRect(50, 120, 271, 20))
        self.checkBox_110.setObjectName("checkBox_110")
        self.checkBox_107 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_107.setGeometry(QtCore.QRect(50, 90, 281, 20))
        self.checkBox_107.setObjectName("checkBox_107")
        self.checkBox_100 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_100.setGeometry(QtCore.QRect(50, 60, 281, 20))
        self.checkBox_100.setObjectName("checkBox_100")
        self.checkBox_101 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_101.setGeometry(QtCore.QRect(350, 90, 281, 20))
        self.checkBox_101.setObjectName("checkBox_101")
        self.checkBox_102 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_102.setGeometry(QtCore.QRect(50, 150, 281, 20))
        self.checkBox_102.setObjectName("checkBox_102")
        self.checkBox_98 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_98.setGeometry(QtCore.QRect(350, 120, 121, 20))
        self.checkBox_98.setObjectName("checkBox_98")
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.listWidget = QtWidgets.QListWidget(self.tab_4)
        self.listWidget.setGeometry(QtCore.QRect(20, 30, 281, 291))
        self.listWidget.setObjectName("listWidget")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(330, 40, 291, 121))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.txtNumeroSerie = QtWidgets.QLineEdit(self.tab_4)
        self.txtNumeroSerie.setGeometry(QtCore.QRect(480, 60, 113, 22))
        self.txtNumeroSerie.setObjectName("lineEdit")
        self.txtNumeroRipetizioni = QtWidgets.QLineEdit(self.tab_4)
        self.txtNumeroRipetizioni.setGeometry(QtCore.QRect(480, 90, 113, 22))
        self.txtNumeroRipetizioni.setObjectName("lineEdit_2")
        self.lblSalvataggio = QtWidgets.QLabel(self.tab_4)
        self.lblSalvataggio.setGeometry(QtCore.QRect(480, 90, 231, 20))
        self.lblSalvataggio.setObjectName("lblSalvataggio")
        self.txtTempoRecupero = QtWidgets.QLineEdit(self.tab_4)
        self.txtTempoRecupero.setGeometry(QtCore.QRect(480, 120, 113, 22))
        self.txtTempoRecupero.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(340, 60, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(340, 90, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(340, 120, 131, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lblUsername = QtWidgets.QLabel(self.tab_4)
        self.lblUsername.setGeometry(QtCore.QRect(20, 6, 281, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblUsername.setFont(font)
        self.lblUsername.setObjectName("label_8")
        self.btnSalvaScheda = QtWidgets.QPushButton(self.tab_4)
        self.btnSalvaScheda.setGeometry(QtCore.QRect(420, 180, 181, 28))
        self.btnSalvaScheda.setObjectName("pushButton_3")
        self.lblInfo1 = QtWidgets.QLabel(self.tab_4)
        self.lblInfo1.setGeometry(QtCore.QRect(310, 30, 421, 21))
        self.lblInfo1.setObjectName("lblInfo1")
        self.lblInfo2 = QtWidgets.QLabel(self.tab_4)
        self.lblInfo2.setGeometry(QtCore.QRect(320, 150, 231, 20))
        self.lblInfo2.setObjectName("lblInfo2")
        self.tabWidget.addTab(self.tab_4, "")
        self.btnInvia = QtWidgets.QPushButton(self.centralwidget)
        self.btnInvia.setGeometry(QtCore.QRect(572, 510, 191, 28))
        self.btnInvia.setObjectName("pushButton")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(170, 41, 110, 21))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(170, 70, 110, 22))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.lblSalvataggio.hide()
        self.lblUsername.setText(self.username)
        self.nascondi()
        self.btnInvia.hide()
        self.listWidget.clicked.connect(self.controllo_salvataggio)
        self.btnSalvaScheda.clicked.connect(self.save_exercise)
        self.dateEdit.setDate(QDate.currentDate())
        self.dateEdit_2.setDate(QDate.currentDate().addMonths(1))
        self.dateEdit.setMinimumDate(QDate.currentDate())
        self.dateEdit_2.setMinimumDate(QDate.currentDate())
        self.tabWidget.tabBarClicked.connect(self.carica_lista)
        self.btnInvia.clicked.connect(self.invia_cliente)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scheda allenamento"))
        self.label_2.setText(_translate("MainWindow", "Data inizio scheda:"))
        self.label_3.setText(_translate("MainWindow", "Data fine scheda:"))
        self.checkBox.setText(_translate("MainWindow", "Distensioni su panca piana con bilanciere"))
        self.checkBox_2.setText(_translate("MainWindow", "Distensioni su panca inclinata con bilanciere"))
        self.checkBox_3.setText(_translate("MainWindow", "Distensioni su panca piana con manubri"))
        self.checkBox_4.setText(_translate("MainWindow", "Distensioni su panca inclinata con manubri"))
        self.checkBox_5.setText(_translate("MainWindow", "Pek dek"))
        self.checkBox_6.setText(_translate("MainWindow", "Croci su panca piana"))
        self.checkBox_7.setText(_translate("MainWindow", "Croci su panca inclinata"))
        self.checkBox_8.setText(_translate("MainWindow", "Pectoral machine"))
        self.checkBox_9.setText(_translate("MainWindow", "Dips press"))
        self.checkBox_13.setText(_translate("MainWindow", "Pek back"))
        self.checkBox_10.setText(_translate("MainWindow", "Croci ai cavi"))
        self.checkBox_12.setText(_translate("MainWindow", "Peck dek inclinato"))
        self.checkBox_11.setText(_translate("MainWindow", "Chest press verticale"))
        self.checkBox_14.setText(_translate("MainWindow", "Pullover"))
        self.checkBox_15.setText(_translate("MainWindow", "Dips"))
        self.checkBox_16.setText(_translate("MainWindow", "Piegamenti alle parallele"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Petto"))
        self.checkBox_17.setText(_translate("MainWindow", "Alzate laterali con macchina"))
        self.checkBox_18.setText(_translate("MainWindow", "Tirate al mento"))
        self.checkBox_19.setText(_translate("MainWindow", "Alzate laterali seduto"))
        self.checkBox_20.setText(_translate("MainWindow", "Scrollate con manubri"))
        self.checkBox_21.setText(_translate("MainWindow", "Lento dietro"))
        self.checkBox_22.setText(_translate("MainWindow", "Pulley con asta lat machine presa larga"))
        self.checkBox_23.setText(_translate("MainWindow", "Distensioni al peck dek"))
        self.checkBox_24.setText(_translate("MainWindow", "Alzate laterali"))
        self.checkBox_25.setText(_translate("MainWindow", "Incroci ai cavi alti con 2 mani"))
        self.checkBox_26.setText(_translate("MainWindow", "Ercolina"))
        self.checkBox_27.setText(_translate("MainWindow", "Alzate laterali ai cavi"))
        self.checkBox_28.setText(_translate("MainWindow", "Lento avanti"))
        self.checkBox_29.setText(_translate("MainWindow", "Pectoral machine"))
        self.checkBox_30.setText(_translate("MainWindow", "Dips"))
        self.checkBox_31.setText(_translate("MainWindow", "Distensioni con manubri"))
        self.checkBox_32.setText(_translate("MainWindow", "Alzate frontali con manubri"))
        self.checkBox_33.setText(_translate("MainWindow", "Tirate al mento stretto"))
        self.checkBox_34.setText(_translate("MainWindow", "Aperture al peck back"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Spalle"))
        self.checkBox_35.setText(_translate("MainWindow", "Rowing machine"))
        self.checkBox_36.setText(_translate("MainWindow", "Pulley"))
        self.checkBox_37.setText(_translate("MainWindow", "Trazioni alla sbarra avanti"))
        self.checkBox_38.setText(_translate("MainWindow", "Pulley alto"))
        self.checkBox_39.setText(_translate("MainWindow", "Trazioni lat machine dietro la nuca"))
        self.checkBox_40.setText(_translate("MainWindow", "Tirate al cavo basso"))
        self.checkBox_41.setText(_translate("MainWindow", "Trazioni alla sbarra dietro la nuca"))
        self.checkBox_42.setText(_translate("MainWindow", "Trazioni alla sbarra presa inversa"))
        self.checkBox_43.setText(_translate("MainWindow", "Pull down dorsale"))
        self.checkBox_44.setText(_translate("MainWindow", "Rematore manubrio"))
        self.checkBox_45.setText(_translate("MainWindow", "Trazioni alla sbarra contrappesi"))
        self.checkBox_46.setText(_translate("MainWindow", "Trazioni lat machine avanti"))
        self.checkBox_47.setText(_translate("MainWindow", "Rematore bilanciere"))
        self.checkBox_48.setText(_translate("MainWindow", "High row "))
        self.checkBox_49.setText(_translate("MainWindow", "Trazioni lat machine avanti presa inversa"))
        self.checkBox_50.setText(_translate("MainWindow", "Dorsy bar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Dorsali), _translate("MainWindow", "Dorsali"))
        self.checkBox_55.setText(_translate("MainWindow", "Panca iperextension"))
        self.checkBox_62.setText(_translate("MainWindow", "Buon giorno"))
        self.checkBox_57.setText(_translate("MainWindow", "Macchina lombari"))
        self.checkBox_65.setText(_translate("MainWindow", "Stacchi da terra gambe flesse"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Lombari"))
        self.checkBox_69.setText(_translate("MainWindow", "Panca iperextension"))
        self.checkBox_63.setText(_translate("MainWindow", "Hip trust"))
        self.checkBox_67.setText(_translate("MainWindow", "Glutes machine"))
        self.checkBox_60.setText(_translate("MainWindow", "Multi hip"))
        self.checkBox_56.setText(_translate("MainWindow", "Squat"))
        self.checkBox_52.setText(_translate("MainWindow", "Tirate al cavo basso con cavigliera"))
        self.checkBox_59.setText(_translate("MainWindow", "Sollevamento gamba panca iper"))
        self.checkBox_66.setText(_translate("MainWindow", "Affondi con manubri"))
        self.checkBox_53.setText(_translate("MainWindow", "Master glutes"))
        self.checkBox_58.setText(_translate("MainWindow", "Ponte con pesi"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Glutei"))
        self.checkBox_74.setText(_translate("MainWindow", "Affondi con manubri"))
        self.checkBox_77.setText(_translate("MainWindow", "Squat lunge"))
        self.checkBox_61.setText(_translate("MainWindow", "Affondi"))
        self.checkBox_76.setText(_translate("MainWindow", "Squat liberi"))
        self.checkBox_79.setText(_translate("MainWindow", "Leg press orizzontale"))
        self.checkBox_72.setText(_translate("MainWindow", "Abductor machine"))
        self.checkBox_54.setText(_translate("MainWindow", "Leg press 45 gradi"))
        self.checkBox_68.setText(_translate("MainWindow", "Squat multipower"))
        self.checkBox_71.setText(_translate("MainWindow", "Leg extension"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Quadricipiti"))
        self.checkBox_88.setText(_translate("MainWindow", "Sollevamenti sulle punte"))
        self.checkBox_70.setText(_translate("MainWindow", "Spinte con le punte al multi power"))
        self.checkBox_80.setText(_translate("MainWindow", "Spinte con le punte al leg press"))
        self.checkBox_81.setText(_translate("MainWindow", "Calf machine"))
        self.checkBox_75.setText(_translate("MainWindow", "Leg curling"))
        self.checkBox_85.setText(_translate("MainWindow", "Leg curling seduto"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Polpacci/femorali"))
        self.checkBox_95.setText(_translate("MainWindow", "Dips press"))
        self.checkBox_86.setText(_translate("MainWindow", "Bicipiti con un braccio al cavo"))
        self.checkBox_82.setText(_translate("MainWindow", "Bicipiti bilanciere"))
        self.checkBox_87.setText(_translate("MainWindow", "Tricipiti dietro al collo in piedi"))
        self.checkBox_83.setText(_translate("MainWindow", "Tricipiti bilanciere presa stretta"))
        self.checkBox_51.setText(_translate("MainWindow", "Spinte in basso presa inversa con braccio al cavo alto"))
        self.checkBox_91.setText(_translate("MainWindow", "Bicipiti manubri"))
        self.checkBox_93.setText(_translate("MainWindow", "Tricipiti busto a 90 al cavo basso"))
        self.checkBox_94.setText(_translate("MainWindow", "Bicipiti alternati in piedi"))
        self.checkBox_90.setText(_translate("MainWindow", "Spinte in basso alla carrucola/fune"))
        self.checkBox_92.setText(_translate("MainWindow", "Panca scott"))
        self.checkBox_84.setText(_translate("MainWindow", "Bicipiti panca inclinata"))
        self.checkBox_64.setText(_translate("MainWindow", "Flesso ed Estensioni della mano"))
        self.checkBox_73.setText(_translate("MainWindow", "Bicipiti sulla coscia"))
        self.checkBox_78.setText(_translate("MainWindow", "Tricipiti dietro al collo seduti"))
        self.checkBox_89.setText(_translate("MainWindow", "Tricipiti alle parallele"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Bicipiti/Tricipiti"))
        self.checkBox_105.setText(_translate("MainWindow", "Plank"))
        self.checkBox_108.setText(_translate("MainWindow", "Sollevamento gambe parallele"))
        self.checkBox_97.setText(_translate("MainWindow", "Piegamenti laterali"))
        self.checkBox_103.setText(_translate("MainWindow", "Torsioni del busto"))
        self.checkBox_110.setText(_translate("MainWindow", "Panca crunch"))
        self.checkBox_107.setText(_translate("MainWindow", "Crunch"))
        self.checkBox_100.setText(_translate("MainWindow", "Addominali machine"))
        self.checkBox_101.setText(_translate("MainWindow", "Sollevamento gambe alla sbarra"))
        self.checkBox_102.setText(_translate("MainWindow", "Crunch inverso"))
        self.checkBox_98.setText(_translate("MainWindow", "Sit up"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("MainWindow", "Addominali"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Scheda Allenamento"))
        self.label_5.setText(_translate("MainWindow", "Numero di serie:"))
        self.label_6.setText(_translate("MainWindow", "Ripetizioni per serie:"))
        self.label_7.setText(_translate("MainWindow", "Recupero per serie:"))
        self.lblUsername.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.btnSalvaScheda.setText(_translate("MainWindow", "Salva "))
        self.lblInfo1.setText(
            _translate("MainWindow", "Inserisci numero di serie, di ripetizioni e tempo di recupero dell\'esercizio"))
        self.lblInfo2.setText(_translate("MainWindow", "Premi \"Salva\" per registrare l\'esercizio"))
        self.lblSalvataggio.setText(_translate("MainWindow", "Salvataggio dell'esercizio effettuato!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Serie/Ripetizioni"))
        self.btnInvia.setText(_translate("MainWindow", "Invia al cliente"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = allenamento_staff()
    ui.setupUi(MainWindow,username= "")
    MainWindow.show()
    sys.exit(app.exec_())
